import '../../../cartillas/domain/report/cartilla_report_config.dart';
import 'cartilla_calibre_bayas_config.dart';

final cartillaCalibreBayasReportConfig = CartillaReportConfig(
  templateKey: CartillaCalibreBayasConfig.templateKeyStatic,
  title: 'CALIBRE DE BAYAS',
  dailyReport: true,
  transposeMetrics: true,
  allowedEstados: const ['borrador', 'pendienteSync', 'enviado', 'error'],
  groupBy: [
    ReportGroupByConfig(
      key: 'lote',
      label: 'Lote',
      path: 'header.${CartillaCalibreBayasConfig.kLoteId}',
    ),
  ],
  columns: [
    ReportColumnConfig.dimension(
      key: 'lote',
      label: 'Lote',
      path: 'header.${CartillaCalibreBayasConfig.kLoteId}',
    ),
    ReportColumnConfig.metric(
      key: 'totalMuestras',
      label: 'Total de Muestras',
      path: 'header.${CartillaCalibreBayasConfig.kLoteId}',
      aggregation: ReportAggregationType.countRows,
      format: 'int',
    ),
    ReportColumnConfig.metric(
      key: 'totalBayasEvaluadas',
      label: 'T.BAYAS EVALUADAS',
      path: 'body.${CartillaCalibreBayasConfig.kTotalBayasEvaluadas}',
      aggregation: ReportAggregationType.sum,
      format: 'int',
    ),
    ..._weightedCalibreColumns,
    ReportColumnConfig.computed(
      key: 'weightedTotal',
      label: 'Acum. Calibres ponderados',
      computation: ReportComputationConfig.sumColumns(
        sourceColumnKeys: [
          for (final source in _calibreSources) 'weighted${source.suffix}',
        ],
      ),
      format: 'decimal2',
      hidden: true,
    ),
    ReportColumnConfig.computed(
      key: 'promCalibreBayas',
      label: 'Prom.Calibre de bayas',
      computation: ReportComputationConfig.divideColumns(
        numeratorColumnKey: 'weightedTotal',
        denominatorColumnKey: 'totalBayasEvaluadas',
      ),
      format: 'decimal2',
    ),
    ReportColumnConfig.metric(
      key: 'totalRacimosEvaluados',
      label: 'Total racimos evaluados',
      path: 'header.${CartillaCalibreBayasConfig.kLoteId}',
      aggregation: ReportAggregationType.countRows,
      multiplier: 3,
      format: 'int',
      hidden: true,
    ),
    ReportColumnConfig.computed(
      key: 'promBayasPorRacimo',
      label: 'Prom.Bayas por racimo',
      computation: ReportComputationConfig.divideColumns(
        numeratorColumnKey: 'totalBayasEvaluadas',
        denominatorColumnKey: 'totalRacimosEvaluados',
      ),
      format: 'decimal2',
    ),
  ],
);

const _calibreSources = [
  (suffix: '0_5', path: CartillaCalibreBayasConfig.kMm0_5, multiplier: 0.5),
  (suffix: '1', path: CartillaCalibreBayasConfig.kMm1, multiplier: 1.0),
  (suffix: '1_5', path: CartillaCalibreBayasConfig.kMm1_5, multiplier: 1.5),
  (suffix: '2', path: CartillaCalibreBayasConfig.kMm2, multiplier: 2.0),
  (suffix: '2_5', path: CartillaCalibreBayasConfig.kMm2_5, multiplier: 2.5),
  (suffix: '3', path: CartillaCalibreBayasConfig.kMm3, multiplier: 3.0),
  (suffix: '3_5', path: CartillaCalibreBayasConfig.kMm3_5, multiplier: 3.5),
  (suffix: '4', path: CartillaCalibreBayasConfig.kMm4, multiplier: 4.0),
  (suffix: '4_5', path: CartillaCalibreBayasConfig.kMm4_5, multiplier: 4.5),
  (suffix: '5', path: CartillaCalibreBayasConfig.kMm5, multiplier: 5.0),
  (suffix: '5_5', path: CartillaCalibreBayasConfig.kMm5_5, multiplier: 5.5),
  (suffix: '6', path: CartillaCalibreBayasConfig.kMm6, multiplier: 6.0),
  (suffix: '6_5', path: CartillaCalibreBayasConfig.kMm6_5, multiplier: 6.5),
  (suffix: '7', path: CartillaCalibreBayasConfig.kMm7, multiplier: 7.0),
  (suffix: '7_5', path: CartillaCalibreBayasConfig.kMm7_5, multiplier: 7.5),
  (suffix: '8', path: CartillaCalibreBayasConfig.kMm8, multiplier: 8.0),
  (suffix: '8_5', path: CartillaCalibreBayasConfig.kMm8_5, multiplier: 8.5),
  (suffix: '9', path: CartillaCalibreBayasConfig.kMm9, multiplier: 9.0),
  (suffix: '9_5', path: CartillaCalibreBayasConfig.kMm9_5, multiplier: 9.5),
  (suffix: '10', path: CartillaCalibreBayasConfig.kMm10, multiplier: 10.0),
  (suffix: '10_5', path: CartillaCalibreBayasConfig.kMm10_5, multiplier: 10.5),
  (suffix: '11', path: CartillaCalibreBayasConfig.kMm11, multiplier: 11.0),
  (suffix: '11_5', path: CartillaCalibreBayasConfig.kMm11_5, multiplier: 11.5),
  (suffix: '12', path: CartillaCalibreBayasConfig.kMm12, multiplier: 12.0),
  (suffix: '12_5', path: CartillaCalibreBayasConfig.kMm12_5, multiplier: 12.5),
  (suffix: '13', path: CartillaCalibreBayasConfig.kMm13, multiplier: 13.0),
  (suffix: '13_5', path: CartillaCalibreBayasConfig.kMm13_5, multiplier: 13.5),
  (suffix: '14', path: CartillaCalibreBayasConfig.kMm14, multiplier: 14.0),
  (suffix: '14_5', path: CartillaCalibreBayasConfig.kMm14_5, multiplier: 14.5),
  (suffix: '15', path: CartillaCalibreBayasConfig.kMm15, multiplier: 15.0),
  (suffix: '15_5', path: CartillaCalibreBayasConfig.kMm15_5, multiplier: 15.5),
  (suffix: '16', path: CartillaCalibreBayasConfig.kMm16, multiplier: 16.0),
  (suffix: '16_5', path: CartillaCalibreBayasConfig.kMm16_5, multiplier: 16.5),
  (suffix: '17', path: CartillaCalibreBayasConfig.kMm17, multiplier: 17.0),
  (suffix: '17_5', path: CartillaCalibreBayasConfig.kMm17_5, multiplier: 17.5),
  (suffix: '18', path: CartillaCalibreBayasConfig.kMm18, multiplier: 18.0),
  (suffix: '18_5', path: CartillaCalibreBayasConfig.kMm18_5, multiplier: 18.5),
  (suffix: '19', path: CartillaCalibreBayasConfig.kMm19, multiplier: 19.0),
  (suffix: '19_5', path: CartillaCalibreBayasConfig.kMm19_5, multiplier: 19.5),
  (suffix: '20', path: CartillaCalibreBayasConfig.kMm20, multiplier: 20.0),
  (suffix: '20_5', path: CartillaCalibreBayasConfig.kMm20_5, multiplier: 20.5),
  (suffix: '21', path: CartillaCalibreBayasConfig.kMm21, multiplier: 21.0),
  (suffix: '21_5', path: CartillaCalibreBayasConfig.kMm21_5, multiplier: 21.5),
  (suffix: '22', path: CartillaCalibreBayasConfig.kMm22, multiplier: 22.0),
  (suffix: '22_5', path: CartillaCalibreBayasConfig.kMm22_5, multiplier: 22.5),
  (suffix: '23', path: CartillaCalibreBayasConfig.kMm23, multiplier: 23.0),
  (suffix: '23_5', path: CartillaCalibreBayasConfig.kMm23_5, multiplier: 23.5),
  (suffix: '24', path: CartillaCalibreBayasConfig.kMm24, multiplier: 24.0),
  (suffix: '24_5', path: CartillaCalibreBayasConfig.kMm24_5, multiplier: 24.5),
  (suffix: '25', path: CartillaCalibreBayasConfig.kMm25, multiplier: 25.0),
  (suffix: '25_5', path: CartillaCalibreBayasConfig.kMm25_5, multiplier: 25.5),
  (suffix: '26', path: CartillaCalibreBayasConfig.kMm26, multiplier: 26.0),
  (suffix: '26_5', path: CartillaCalibreBayasConfig.kMm26_5, multiplier: 26.5),
  (suffix: '27', path: CartillaCalibreBayasConfig.kMm27, multiplier: 27.0),
  (suffix: '27_5', path: CartillaCalibreBayasConfig.kMm27_5, multiplier: 27.5),
  (suffix: '28', path: CartillaCalibreBayasConfig.kMm28, multiplier: 28.0),
  (suffix: '28_5', path: CartillaCalibreBayasConfig.kMm28_5, multiplier: 28.5),
  (suffix: '29', path: CartillaCalibreBayasConfig.kMm29, multiplier: 29.0),
  (suffix: '29_5', path: CartillaCalibreBayasConfig.kMm29_5, multiplier: 29.5),
  (suffix: '30', path: CartillaCalibreBayasConfig.kMm30, multiplier: 30.0),
  (suffix: '30_5', path: CartillaCalibreBayasConfig.kMm30_5, multiplier: 30.5),
  (suffix: '31', path: CartillaCalibreBayasConfig.kMm31, multiplier: 31.0),
  (suffix: '31_5', path: CartillaCalibreBayasConfig.kMm31_5, multiplier: 31.5),
  (suffix: '32', path: CartillaCalibreBayasConfig.kMm32, multiplier: 32.0),
  (suffix: '32_5', path: CartillaCalibreBayasConfig.kMm32_5, multiplier: 32.5),
  (suffix: '33', path: CartillaCalibreBayasConfig.kMm33, multiplier: 33.0),
  (suffix: '33_5', path: CartillaCalibreBayasConfig.kMm33_5, multiplier: 33.5),
  (suffix: '34', path: CartillaCalibreBayasConfig.kMm34, multiplier: 34.0),
  (suffix: '34_5', path: CartillaCalibreBayasConfig.kMm34_5, multiplier: 34.5),
  (suffix: '35', path: CartillaCalibreBayasConfig.kMm35, multiplier: 35.0),
  (suffix: '35_5', path: CartillaCalibreBayasConfig.kMm35_5, multiplier: 35.5),
  (suffix: '36', path: CartillaCalibreBayasConfig.kMm36, multiplier: 36.0),
  (suffix: '36_5', path: CartillaCalibreBayasConfig.kMm36_5, multiplier: 36.5),
  (suffix: '37', path: CartillaCalibreBayasConfig.kMm37, multiplier: 37.0),
  (suffix: '37_5', path: CartillaCalibreBayasConfig.kMm37_5, multiplier: 37.5),
  (suffix: '38', path: CartillaCalibreBayasConfig.kMm38, multiplier: 38.0),
];

final _weightedCalibreColumns = [
  for (final source in _calibreSources)
    ReportColumnConfig.metric(
      key: 'weighted${source.suffix}',
      label: 'Acum. ${source.multiplier}mm',
      path: 'body.${source.path}',
      aggregation: ReportAggregationType.sum,
      multiplier: source.multiplier,
      format: 'decimal2',
      hidden: true,
    ),
];
